### ISSUE TITLE
installed_languages should not be required

### ISSUE THREAD

**Issue by rchl** [sublime-treesitter/TreeSitter#10]
Making `installed_languages` required in schema IMO doesn't make sense since it's not required in user settings because it's inherited from default settings so not having it should not raise a warning.

https://github.com/sublime-treesitter/TreeSitter/blob/20ffa941686ad7698f9daee24fc4b28a7202e3c7/sublime-package.json#L110

**Comment by kylebebak** [comment]
Agreed, thanks for catching this. This is fixed in https://github.com/sublime-treesitter/TreeSitter/releases/tag/1.5.1
