### ISSUE TITLE
question: how to install new grammar?

### ISSUE THREAD

**Issue by bokunodev** [sublime-treesitter/TreeSitter#16]
how to add new grammar that isn't listed in the menu?
where should i put `grammar.js` and the parser files?

**Comment by kylebebak** [comment]
Some of the info you're looking for is here in the README: https://github.com/sublime-treesitter/TreeSitter?tab=readme-ov-file#manage-your-own-language-repos-and-binaries

To manage your own languages, you need to do a few things in the STS settings. Search for `Preferences: TreeSitter Settings` in the command palette

- Set `python_path` to an external Python 3.8 executable with a working C compiler. This way STS can compile its own TS language binaries. The Python that ships with Sublime Text can't compile TS languages
- If the language you want to install [isn't in this list here](https://github.com/sublime-treesitter/TreeSitter/blob/0639b5ec56fda9c8c599a2e3b38130a9a97aaa1a/src/utils.py#L189-L236), add `language_name_to_repo` to your settings, and also add `language_name_to_scopes`
  - These settings dicts are merged with the dicts in `src/utils.py`
- STS automatically downloads the language from its GitHub repo, builds the language binary, and uses this language for scopes defined in `language_name_to_scopes`
  - You don't have to manually add `grammar.js` files
  - To see where languages are installed on your machine, restart ST and open the ST console (**View > Show Console**); STS logs this location on startup

Here's an example of how to do this for e.g. [dart](https://github.com/UserNobody14/tree-sitter-dart)

Your settings would look something like this. Then you could run `TreeSitter: Install Language` and install `dart`. STS would download the language repo, build the language binary, instantiate the language, and use it to parse code in any buffer with a scope of `source.dart`

```json
{
  "python_path": "~/.pyenv/versions/3.8.13/bin/python",
  "installed_languages": [
    "python",
    "json",
  ],
  "language_name_to_repo": {
    "dart": {"repo": "UserNobody14/tree-sitter-dart"},
  },
  "language_name_to_scopes": {
    "dart": [
      "source.dart",
    ],
  },
}
```
